name: PR

on:
  pull_request:

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/.github/workflows/go-prepare.yml@b8f28cd674873379b1c03de8f3144a592a21cc9e
    with:
      only-dependencies: true

  checks:
    name: Checks
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/go-checks.yml@b8f28cd674873379b1c03de8f3144a592a21cc9e